### ISSUE TITLE
Add documentation and samples

### ISSUE THREAD

**Issue by daniel-lerch** [losttech/Settings#1]
This library looks amazing!
Searching for a replacement for `app.config` for [Vocup](https://github.com/daniel-lerch/vocup), I had already started implementing an own solution when I saw this library.

To get started, a README with a short explanation to use this library would be useful. The code looks good but without comments or extensive unit tests it's hard to guess what some interfaces like `IFreezerFactory` were designed for.

This library does not be actively developed anymore. Would you still accept pull requests for updates?

**Comment by lostmsu** [comment]
Sure, yes, I'd take pull requests. Note though, that I discovered a few issues with the library, and currently recommend to store settings in a SQLite database instead.

**Comment by lostmsu** [comment]
@daniel-lerch FYI, I modernized project a bit, added XML docs, and published a new version.

**Comment by lostmsu** [comment]
@daniel-lerch added README in ae4720fd7de9eed4ed4bb652fbd8e87b9ae41110

**Comment by daniel-lerch** [comment]
Thank you very much for this fast reaction and your documentation. I have rewritten Vocup's settings using this library and did not notice any problems. Can you give me a hint what to test in order to reproduce problems you referred to? Otherwise I would schedule a release with this library for settings.

**Comment by lostmsu** [comment]
1. Change a few settings and close the app quickly.
2. Try changing different kinds of settings, and check that the final state persisted properly (take settings page screenshot and compare to the XML contents).
